### ISSUE TITLE
no nifty=1.0.9 for Win64 as of Oct '21

### ISSUE THREAD

**Issue by Mrc010** [hci-unihd/plant-seg#101]
On Windows 10 with miniconda3 (and Python 3.7, 3.8, 3.9), when executing  

`conda create -n plant-seg -c pytorch -c conda-forge -c lcerrone -c abailoni -c cpape -c awolny pytorch nifty=1.0.9 plantseg
`

I get the error 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - nifty=1.0.9
```
and 

`conda search nifty -c abailoni` only gives Version 1.0.8

`conda create -n plant-seg -c pytorch -c conda-forge -c lcerrone -c abailoni -c cpape -c awolny pytorch nifty=1.0.8 plantseg`

works for me, but I don't know whether it is important to have 1.0.9...

**Comment by lorenzocerrone** [comment]
Hi @Mrc010, sorry for the long waiting; we were completely taken from another project. 

Yes, indeed, the command-line installation instruction is only for Linux, and we have been working to fix all Windows missing requirements. Hopefully, a fully native Windows version is coming in January. 

I have not tested `nifty=1.0.8` but I think that that GASP would not work. multicut should work fine.

This should also work
`conda create -n plant-seg -c pytorch -c conda-forge -c lcerrone -c abailoni -c cpape -c awolny pytorch plantseg`
But, again, you will be able to use only multicut segmentation. 

Best, 

Lorenzo

**Comment by lorenzocerrone** [comment]
Hi @Mrc010,

We just finished fixing all compatibility issues. Now plantseg should fully work on windows. 

Best regards,
Lorenzo
