### ISSUE TITLE
Plantsegs 3D Unet step produces images with a grid pattern on top, which lead to wrong graph partitioning results

### ISSUE THREAD

**Issue by Nablaaa** [hci-unihd/plant-seg#106]
Hello everyone,

When I was using plantseg for a 401x300 pixel image in 3 dimensions with 78 slides in z with (z,y,x) = (1 µm, 0.17 µm, 0.17 µm), I tried the "generic_light_sheet_3d_unet" model  for segmenting embryonic mouse cells (also light sheet microscopy).

Settings:
Mirror padding: [16, 32, 32]
Patch: [32, 128, 128]
Stride: [20, 100, 100]

The results are added to this entry(photo). Plantseg creates an image with a grip pattern on top and some obscure intensities on the bottom right and to the left of the cells. The cells itself look quite good.
The next step (GASP) than do not work properly and only a single cell is detected.
I think that I misunderstood something by the choice of the settings. Could someone help me to understand mirror padding, patch and stride and eventually give a better combination of parameters?

Thank you in advance :)

![Plantseg-GridPattern](https://user-images.githubusercontent.com/49586931/146774896-a04a5627-d410-44ac-a3d0-d7e8ff442aa3.jpg)

**Comment by lorenzocerrone** [comment]
Hi! 

Thanks for testing PlantSeg :) 

I think that the problem might be the stride too large, could you test if the problem is solved if you use Stride: [16, 64, 64]? 

Best,
Lorenzo

**Comment by Nablaaa** [comment]
Thank you so much @lorenzocerrone !
I tried a [8, 64,64] stride now and it worked out.
Is it, because the fields were not overlapping when the stride is chosen too big?

Best wishes,
Eric

**Comment by lorenzocerrone** [comment]
Great :) 

Yes, you are exactly right. If I remember correctly, the `patch - stride > padding (or the halo)` is sufficient to avoid this grid pattern. In practice, it is always better to use a much smaller stride than the theoretical limit to reduce artifacts over the overlapping tiles.

Best,
Lorenzo
