### ISSUE TITLE
Change 'Stride' to Fast (less overlap, potential block artifacts), Standard, Slow (high overlap, better precision)

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#11]

**Comment by lorenzocerrone** [comment]
Now there are three options 
"Accurate (slower)": 0.5 * patch size
 "Balanced": 0.75 * patch size
 "Draft (faster)": 0.9* patch size
Do let me know if you agree with the naming and ratios

PS from config specifying a list of strides still works
