### ISSUE TITLE
2D segmentation of root meristem

### ISSUE THREAD

**Issue by AlexStroh-git** [hci-unihd/plant-seg#113]
Dear authors,

I'm trying to run plant-seg on 2d confocal images of root meristems stained with FM4-64. I tried the confocal_2D_unet_bce_dice and the confocal_PNAS_2d model. Both models run smoothly after adjusting rescaling and patch size. The converted Prediction and Segmentation yield only tiffs with no information. Is there anything I forgot or can change with the settings or the input data that might solve this problem so i can get a proper watershed segmentation?
Here is one image as jpg that i used as input data...
![WS_light](https://user-images.githubusercontent.com/64042260/161537294-f8272ba1-0896-4c4f-9e3f-4a8e7be93959.jpg)

**Comment by lorenzocerrone** [comment]
Hi,

Sorry for the very very late answer. I must have overlooked it. 

Have you tried to open the h5 file using Fiji? Could you share the plant-seg configuration you used?

Best,
Lorenzo

**Comment by qin-yu** [comment]
@lorenzocerrone This GitHub user has been inactive for a long time. The software has changed a lot since then. Maybe we can close this issue.
