### ISSUE TITLE
Input_paths cannot be empty

### ISSUE THREAD

**Issue by ZH-GAO** [hci-unihd/plant-seg#114]
Hi,
I have an error "Input file paths cannot be empty". While i have typed in the file path
Anyone knows how to solve it??
![Screenshot from 2022-07-20 11-06-54](https://user-images.githubusercontent.com/109642602/179893744-231cdf0f-287d-4ed1-b4bf-f9948c7e84ea.png)

**Comment by lorenzocerrone** [comment]
My suggestion in this case is to either use a 2D model and patch size (1, 160, 160).. or to use rescaling (2, 1, 1) to increase the number of z stacks. 

I hope this helps you out. I close the issue for now, but feel free to reopen it if you have more issues.
