### ISSUE TITLE
Launching plant-seg after installation

### ISSUE THREAD

**Issue by clintondurney** [hci-unihd/plant-seg#120]
Hi Plant-Seg, 

I installed plant-seg via the conda installation, but upon launching it for the first time I get the following error:

Traceback (most recent call last):
  File "/home/cdurney/miniconda3/envs/plant-seg/bin/plantseg", line 6, in <module>
    from plantseg.run_plantseg import main
  File "/home/cdurney/miniconda3/envs/plant-seg/lib/python3.9/site-packages/plantseg/run_plantseg.py", line 3, in <module>
    from plantseg.pipeline.raw2seg import raw2seg
  File "/home/cdurney/miniconda3/envs/plant-seg/lib/python3.9/site-packages/plantseg/pipeline/raw2seg.py", line 3, in <module>
    from plantseg.dataprocessing.dataprocessing import DataPostProcessing3D
  File "/home/cdurney/miniconda3/envs/plant-seg/lib/python3.9/site-packages/plantseg/dataprocessing/dataprocessing.py", line 6, in <module>
    from vigra.filters import gaussianSmoothing
  File "/home/cdurney/miniconda3/envs/plant-seg/lib/python3.9/site-packages/vigra/__init__.py", line 118, in <module>
    import vigra.analysis as analysis
ImportError: /home/cdurney/miniconda3/envs/plant-seg/lib/python3.9/site-packages/vigra/../../../libemon.so.1.3.1: undefined symbol: _ZN8ClpModel13setColumnNameEiRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 

I get the same error on an Ubuntu 20.04 virtual machine and a dedicated Ubuntu 20.04 machine. However, neither have a dedicated GPU. From the README, it appears that the GPU is optional. 

Thanks in advance for your help.

Best,
Clinton

**Comment by lorenzocerrone** [comment]
Hi Clinton,

Sorry for the late answer. I was two weeks out of the office. 

Thanks for letting me know about this error. There is a conflict between two dependencies of plantseg. In the meanwhile I will fix this properly. You can install plantseg using `mamba`.

Just install `mamba` in your base environment.
```
conda install -c conda-forge mamba
``` 
And then install plant-seg by running
```
mamba create -n plant-seg -c pytorch -c conda-forge -c lcerrone -c awolny pytorch=1.9 pytorch-3dunet=1.3.7 plantseg
```

I will update you here when I fix the issue. 


Best,
Lorenzo

PS: A major release of plant-seg will come out in the next few days https://github.com/hci-unihd/plant-seg/tree/plantseg_napari
It will be much easier to use and uses napari as a built-in viewer. I think it would be worth updating it as soon as we release it :)

**Comment by hongw579** [comment]
I got the same error. Can it be solved by installation through `mamba`? Thank you!

**Comment by clintondurney** [comment]
Yes, [lorenzocerrone](https://github.com/lorenzocerrone)'s reply on Sept 26 worked for me.
