### ISSUE TITLE
Problem running plant-seg on batch mode

### ISSUE THREAD

**Issue by lcferme** [hci-unihd/plant-seg#121]
Hello, 

When I try to run plant-seg on multiple images in a folder, after completing the predictions for the first image, I get the following message:
[...]
 `File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper`
`File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper`
`File "h5py\h5f.pyx", line 106, in h5py.h5f.open`
`OSError: Unable to open file (file signature not found)`

This happens both when I use the GUI and when I try to run plant-seg from the terminal. Do you know what is the problem?
Thanks!

Lucrezia

**Comment by lorenzocerrone** [comment]
Hi Lucrezia,

I hope I can help you with your request. 

From the error message it seems that the error comes from a wrongly formatted or corrupted h5 file. 
Could you try to open the same h5 file using another software like fiji? 

When does the error occur? (in the preprocessing, in the cnn predictions or in the segmentation)

Best,
Lorenzo

**Comment by qin-yu** [comment]
Hi @lcferme, thanks for reporting. Are you still using PlantSeg? The software has changed a lot. Maybe I'll close this issue if there is no more follow-up.
