### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by e-tomato** [hci-unihd/plant-seg#123]
Hi Plant-Seg, 

After I installed plantseg via mamba and run it, I get the following error. I tried to change the config file, but I always got the same error. Could you help to figure out why? 

Thanks in advance for your help.

Best,

`plantseg --config config.yaml`
" Traceback (most recent call last):
 /envs/plant-seg/bin/plantseg", line 10, in <module>
    sys.exit(main())
 /envs/plant-seg/lib/python3.9/site-packages/plantseg/run_plantseg.py", line 27, in main
    config = load_config(args)
 /envs/plant-seg/lib/python3.9/site-packages/plantseg/run_plantseg.py", line 16, in load_config
    config = yaml.load(open(args.config, 'r'), Loader=yaml.FullLoader)
 /envs/plant-seg/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
 /envs/plant-seg/lib/python3.9/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config.yaml", line 4, column 14 "

**Comment by lorenzocerrone** [comment]
Hi, 

Sorry for the late answer. 
Could you share your config file, it seems that there is a syntax error there. 

Best,
Lorenzo
