### ISSUE TITLE
Errors with PlantSeg implementation

### ISSUE THREAD

**Issue by upasana99** [hci-unihd/plant-seg#127]
Hi,
I am trying to use plantseg gui to perform segmentation of cells in confocal images. 

I am however, encountering this issue with patch size constantly. The size of the images is (1024,1024,3,30) as they are zstack image.s When I give the patch size as (1024,1024, 3), I get the following error. 
![image](https://user-images.githubusercontent.com/53419878/226212139-65c2a942-d35e-4a8c-acf4-5f91feb668b8.png)

I figured since it is a zstack .tif images. I converted them to grayscale to see if that works but it still throws the same error. 

Any help is appreciated!

**Comment by lorenzocerrone** [comment]
Hi, 

I think there are two problems here. The first is that the channel order is not what plantseg expects. Plantseg expects z-stacks to be ordered as (z, x, y), but yours, if I understand correctly, is (x, y, z, c) or  (x, y, c, z). 

The second problem is that three z-stack slices are insufficient to run a 3dUnet, so you should run a 2d model. 

I hope this feedback can help you, don't hesitate to ask more questions! 

Best,
Lorenzo

**Comment by upasana99** [comment]
Hi, 

Thank you for the feedback. I tried using the command line method. I was able to run PlantSeg. However, while PlantSeg ran on the .tiff I used, It gave a pitch dark image as segmentation results.
I have attached the post processing result image and a zip file containing config.yaml file that I used to run PlantSeg.

Kindly advise if I need to make any changes to the config file in order to successfully run PlantSeg.

![image](https://user-images.githubusercontent.com/53419878/229858438-46313b67-433a-48da-8d04-5e1a4c8d49b5.png)
[config.zip](https://github.com/hci-unihd/plant-seg/files/11150852/config.zip)

Any help is appreciated! 
Thanks in advance!

Best,
Upasana

**Comment by lorenzocerrone** [comment]
Hi Upasana,

The config seems formatted correctly, but I don't have enough information to understand the issue.  

If this would be fine with you, could you share with me (either here or via email) the tiff file you are using?

Best,
Lorenzo

**Comment by upasana99** [comment]
Hi Lorenzo,

Thank you for your reply and feedback. I have the following issue:

Upon running plantseg on the attached input image, I get 2 output .tiff
files which are also attached.

The multicut output image is pitch dark but there is a post-processing
image which seems to have some results.

Here is the drive link with the input and output files.
https://drive.google.com/drive/folders/1f-rUJOMlQGJweffElb9FYwviGki2qa83?usp=sharing

Thanks in advance!

Best Regards,
Upasana

**Comment by upasana99** [comment]
Hi Lorentzo,

Just a follow up on this issue!

Thanks and regards,
Upasana

**Comment by lorenzocerrone** [comment]
Hi Upasana,

Sorry for the late answer, but we have been working on a lot of small improvements for the next release for the last few days.

The image that you posted on Drive is not empty. I think this is an issue with the application you are using to open it. Have you tried to visualize the results in Fiji? 


I played a little with the sample you sent me, and using the `ovules_ds3x` model and `GASP` with default parameters this the result: https://drive.google.com/drive/folders/1Hx5OQAkdNpn8vo2rQQy-oVCG9Q9oKfTq?usp=share_link

Another tip, have you tried using plantseg with the napari viewer? 
If you have plantseg > 1.5.0, just try to start plantseg as:
```
plantseg --napari
```
This should be easier for experimenting with plantseg, unfortunately, we have not yet documented this properly.
