### ISSUE TITLE
More stable and manteinable upload/download location for models

### ISSUE THREAD

**Issue by lorenzocerrone** [hci-unihd/plant-seg#134]
At the moment, the models are stored in a private cloud. It would be great to move to something like zendo or similar.

The ideal place should be stable and easy to access for all plantseg maintainers. @wolny Any idea?

**Comment by wolny** [comment]
Yes, I think zenodo would be the best place for that and since we have a lot of plantseg models uploaded there already (as part of the bioimage.io initiative), I'll just migrate the remaining models there and change the plantseg client accordingly.
