### ISSUE TITLE
Error during layer export

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#136]
`root_name` not set in the layer metadata:

```
File ~/workspace/plant-seg/plantseg/viewer/widget/io.py:319, in export_stacks(images=[(<Labels layer 'image_cropped_generic_confocal_3D_unet_MultiCut'>, '')], directory=PosixPath('/home/adrian'), export_format='tiff', rescale_to_original_resolution=True, data_type='uint16', workflow_name='confocal_segmentation')
    318 # add step to the workflow dag
--> 319 root_name = image.metadata['root_name']
        image = <Labels layer 'image_cropped_generic_confocal_3D_unet_MultiCut' at 0x7f6fb995a380>
    320 input_keys = (image.name,
    321               'out_stack_name',
    322               'out_directory',
    323               f'{root_name}_voxel_size',
    324               f'{root_name}_voxel_size_unit'
    325               )

KeyError: 'root_name'
````

**Comment by lorenzocerrone** [comment]
Was the raw image imported from the napari gui or from the plantseg widget?

**Comment by wolny** [comment]
the image to be exported is the segmentation layer, so it's chosen via the export widget. it's weird though, because it seems to depend on the entry point to the export: when I export directly after segmentation it works, but when I do something else before (e.g. proofreading) it errors. I'll keep digging...

**Comment by lorenzocerrone** [comment]
I have fixed the bug that causes the crash in my PR. So this does now not fail if the metadata is not there but gives an arbitrary label `unknown`. This does not affect the exported file. The only effect is in the headless workflow (that will fail)

But in your case, the image comes from `image_cropped_generic_confocal_3D_unet_MultiCut`, so the last step was just a simple MultiCut. This should not have failed. Did you import the image from the widget or the Napari built-in import?

**Comment by wolny** [comment]
I've imported from the widget
