### ISSUE TITLE
Confocal Ovules ds2x and ds3x are the same 

### ISSUE THREAD

**Issue by lorenzocerrone** [hci-unihd/plant-seg#138]
Hey Adrian @wolny,

I have noticed something weird in the new plantseg models. The generic confocal, ds2x ovules and the ds3x ovules have all the same weights (see screenshot)
![Screenshot from 2023-04-05 16-20-39](https://user-images.githubusercontent.com/23013839/230110054-f0b21d48-ff7a-40c5-be3a-959532a060f8.png)

Also I just noticed that the generic confocal has  not the same weights as the old version (the one in the own cloud).

I think there must have been some error in moving them to zenodo.
Could you please look at it?

**Comment by wolny** [comment]
hey @lorenzocerrone, thanks for looking into this! `generic confocal` is just an alias for `ds2x ovules`, so that's expected but ` ds3x ovules` looks like a bug. I'll compare with the old weights we still have on ownCloud

**Comment by wolny** [comment]
indeed! I've just checked the weights from owncloud: `ds2x ovules` had the weights from `ds3dx`. Really nice that you've checked that, otherwise the performance would silently be lower than before :raised_hands:.
I'll re-upload the correct weights to zenodo and make a PR.
