### ISSUE TITLE
reading zarrs

### ISSUE THREAD

**Issue by Mohinta2892** [hci-unihd/plant-seg#143]
Hi!

I am wondering if the code allows reading pmaps from within a zarr.
As of now, the idea is to segment pmaps stored in a dataset inside a zarr file instead of hdf file via the command line 
`plantseg --config config.yaml`

Any help is really appreciated!

Best,
Samia

**Comment by wolny** [comment]
Hi Samia,

that would be a nice feature, and we could definitely make that happen. Could you provide us with a sample zarr file we could use to test this new functionality?

**Comment by lorenzocerrone** [comment]
Yes, I agree, we can definitely make it happen! With the current plantseg  structure is quite straight forward to add support for more file types.

**Comment by Mohinta2892** [comment]
Many thanks both. If it can be added as a new feature that would be really helpful.

Please find the data [here] (https://mrclmbcamacuk-my.sharepoint.com/:f:/g/personal/smohinta_mrc-lmb_cam_ac_uk/EonqXZv93qdKnKF7Kj-0ORwBwAFCP7W2kXprYPcQGnS3Dw?e=pxmFUY)

The above link also contains an implementation of zarr read/write (not tested thoroughly) that I wrote today to extend the io functionality locally. However, I was not really sure of plant-seg's control flow. Feel free to use it.

Best,
Samia

**Comment by lorenzocerrone** [comment]
Hi Samia,

I checked your `zarr.py,` and looks great!

I think it would be fair (also to give you credit) if you open a PR to plantseg, adding the file in `plantseg/io/.` I will make it fit the rest of the plantseg code and ship it with the next release. 

Best,
Lorenzo

**Comment by lorenzocerrone** [comment]
Thanks! I will merge it and fixed it in a new branch. 
I will keep you posed on when this is released
