### ISSUE TITLE
`create_tiff()` changes the input numpy array, which may cause problems

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#153]
If this function is not the last function you call, it may cause unexpected errors as it modifies the original numpy array:

https://github.com/hci-unihd/plant-seg/blob/f09ef0e5260841280572657f0abe307a87263aa5/plantseg/io/tiff.py#L146

**Comment by lorenzocerrone** [comment]
True! Thanks Qin

I have fixed it :)
