### ISSUE TITLE
No compression for saving TIFF file

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#155]
I'm using the IO module from PlantSeg for my own project these days so I also noticed that, for the TIFF labels, using `compression='zlib'` in `create_tiff()` may significantly save disk space:
```python
    tifffile.imwrite(
        path,
        data=stack,
        dtype=stack.dtype,
        imagej=True,
        resolution=resolution,
        metadata={'axes': 'TZCYXS', 'spacing': spacing, 'unit': voxel_size_unit},
        compression='zlib',  # I believe 'zlib' is the classic one, there are more efficient options tho
    )
```

**Comment by lorenzocerrone** [comment]
Sounds like a good idea! thanks! I can't add it at the moment, but I will fix this for the next release :)
