### ISSUE TITLE
Error after updating plantseg

### ISSUE THREAD

**Issue by athulrv** [hci-unihd/plant-seg#168]
![plantseg error](https://github.com/hci-unihd/plant-seg/assets/49643312/a66fa469-00fb-4bc5-b971-20dd60f3da09)

2023-11-02 17:14:42,545 - key: device has got value: cuda, but torch can not detect a valid cuda device. defaulting default value: cpu
2023-11-02 17:14:42,545 - key: 'stride_ratio' is missing, plant-seg is trying to use a default.
2023-11-02 17:14:42,545 - key: stride_ratio has got value: None, but value must be a float (or integer). defaulting default value: 0.75

**Comment by athulrv** [comment]
error persist even if i use old working config file or change to cpu. it seems like the error is associated with the update. @qin-yu @wolny

**Comment by qin-yu** [comment]
@athulrv It is related to previous update of PlantSeg (a few months ago maybe?), but not due to the update I did for this paper. You can either modify the config I sent in Slack on Tuesday or use the templates from https://github.com/hci-unihd/plant-seg/tree/master/examples

**Comment by athulrv** [comment]
using this config file didnt help. Also tried to remove plantseg and install again. no change. 
is there a way to remove plantseg and its dependencies completely? i just deleted the env folder to remove it.

**Comment by qin-yu** [comment]
For the record, Athul encountered this different error for `plantseg --config` pipeline:

![image](https://github.com/hci-unihd/plant-seg/assets/17722010/d509687f-89de-46cb-b4b8-7c0000e1cd70)

I guess this is because we haven't released the latest PlantSeg yet and the installation guide only gives Athul v1.6.0, maybe we could release a tag or version just for the paper after I finalise the default model thing? @wolny

**Comment by wolny** [comment]
hey Qin. Yes, if we want to use the new keys then we need to release. I'll do a minor release now and let you know

**Comment by wolny** [comment]
I've released the new version (v1.6.1). Now the new keys that @qin-yu introduces should not cause any issues. Please update your plantseg @athulrv

**Comment by athulrv** [comment]
![with terminal_its_using cpu , but working](https://github.com/hci-unihd/plant-seg/assets/49643312/7e5f1052-497b-4ea7-a6b5-a45df94c7a2f)
![error_after_updating](https://github.com/hci-unihd/plant-seg/assets/49643312/8432b6e9-3c14-4d63-a95c-00fd94ba6f1e)

I updated to 1.6.1 
Now plantseg has similar error in gui, with terminal its working but with cpu. 
@wolny

**Comment by wolny** [comment]
Hi @athulrv, thanks for letting me know. Regarding the 'cpu'. Could you tell me what `conda list` command tells about the `pytorch` version installed? I'm afraid that `pytorch-cpu` was wrongly installed after the update. I'd recommend you install plantseg from scratch following instructions in https://github.com/hci-unihd/plant-seg#install-plantseg-using-mamba.

As for the old UI: we don't use the `mirror_padding` option anymore in the config. But anyway, it should be a warning, not an error. As a workaround please remove the `mirror_padding` options from the config you're using and the default config, which can be found under `~/.plantseg_models/configs/config_gui_last.yaml`.

**Comment by athulrv** [comment]
Hi @wolny 
![image](https://github.com/hci-unihd/plant-seg/assets/49643312/0dad9206-e104-47f1-a6f0-a2aba4ab75ed)

The error was after I installed plantseg fresh using mamba.

**Comment by qin-yu** [comment]
@athulrv did you try putting `CUDA_VISIBLE_DEVICES=0 ` in front of `plantseg --config`?

**Comment by Buglakova** [comment]
Hello. For me installing `plantseg` with the command given in documentation installed the cpu version only. Adding the appropriate version of `cudatoolkit` explicitly solved it @athulrv:

`mamba create -n plant-seg -c pytorch -c nvidia -c conda-forge -c lcerrone plantseg pytorch-cuda=11.7 cudatoolkit`
