### ISSUE TITLE
PlantSeg latest version, having issue with using CUDA from GUI. 

### ISSUE THREAD

**Issue by athulrv** [hci-unihd/plant-seg#172]
I installed Plantseg using "mamba create -n plant-seg -c pytorch -c nvidia -c conda-forge -c lcerrone plantseg pytorch-cuda=11.7 cudatoolkit". My cuda version is 11.7. I still have this issue that plantSeg is using CPU, not cuda. This happened after several reinstallations as well. 

![cuda 11 7](https://github.com/hci-unihd/plant-seg/assets/49643312/87699ea6-3270-438f-9ab7-96119c4bc249)

**Comment by lorenzocerrone** [comment]
Hi Athul, yes I had the same issue. Try the new installation command, it should work

**Comment by athulrv** [comment]
mamba create -n plant-seg -c pytorch -c nvidia -c conda-forge -c lcerrone pytorch pytorch-cuda=11.8 pyqt plantseg

i should replace 11.8 by 11.7 in my case right?

**Comment by lorenzocerrone** [comment]
No, 11.8 should work just fine for you. The version is taken from the official Pytorch install guide; between 11.7 and 11.8, there are small differences, but what we use in the plants does not matter.

**Comment by athulrv** [comment]
Great. Its finally working fine. Thanks a lot.
