### ISSUE TITLE
Support for GUI dataset/channel selection, follow #165

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#173]
I plan to add these to GUI first then Napari. Do I need to watch out for something (cus I have limited experience with GUI)?

- Use case: Alyona wanted to find out if PlantSeg can be used for her images
- Her steps:
  1. Install PlantSeg and run all models on the same images
  2. Check which model give the best segmentation and probability map
  3. She finds my generic plant nuclei model is the only capable model, to my surprise
  4. But GUI can't give segmentation for some 2-channel network output

Maybe we should spend some time adding this to GUI.

**Comment by wolny** [comment]
hey @qin-yu, as disucssed with @lorenzocerrone let's implement it *only* for the multi-channel network output:
1. In legacy GUI, we should add the option you've added in config
2. In the napari GUI we should load the multi-channel output from the network in separate layers (one layer per channel) and the rest will work out of the box

**Comment by qin-yu** [comment]
I think I fixed this. Please check #184 @wolny @lorenzocerrone

**Comment by lorenzocerrone** [comment]
Yes we can close this

**Comment by qin-yu** [comment]
Wait a minute @lorenzocerrone It's not actually fixed until #184 is merged 🤣 I meant please review and see if it's fixed, though I thought it's fixed.

**Comment by lorenzocerrone** [comment]
Yeah sorry, I should have explained more :D 

That part I have reviewed yesterday when we met and it was fine. But I will do the full PR review tomorrow :)
