### ISSUE TITLE
test the network using tif image of root/leaf 

### ISSUE THREAD

**Issue by sajidullah124** [hci-unihd/plant-seg#18]
I tried to test the network using a root/leaf tissue image (tif ) at cellular resolution. I got error. it produce .h5 prediction for each test file which is not in the folder. can some one tell me how to run a test image from a custom data?

**Comment by wolny** [comment]
hi @sajidullah124,

thanks for reporting the issue. From what you wrote however it's hard to say what went wrong.
Could you send us the following:
1. Copy of the error that you've got.
2. A config file of the pipeline (can be found under `~/.plantseg_models/configs/config_gui_last.yaml`)

**Comment by wolny** [comment]
hey @sajidullah124, could you provide us with more information about your issue, so that we could help you resolve it?

**Comment by wolny** [comment]
Closing this one, due to lack of additional inpu
