### ISSUE TITLE
Wiki doc path update on python API

### ISSUE THREAD

**Issue by jackyko1991** [hci-unihd/plant-seg#181]
Update on wrongly documented python API:  https://github.com/jackyko1991/plant-seg.wiki.git

I cannot directly edit the original wiki or create pull request. The wiki merging may follow the guide for repo owner here: https://gist.github.com/larrybotha/10650410#merging-changes

**Comment by qin-yu** [comment]
Hey @jackyko1991 thanks for updating!

This is the link to Jack's Wiki: https://github.com/jackyko1991/plant-seg/wiki

```
$ git diff HEAD~3 HEAD
diff --git a/Home.md b/Home.md
index 8ab7493..0391dbe 100644
--- a/Home.md
+++ b/Home.md
@@ -14,4 +14,4 @@ segmentation. We implemented four different algorithms for segmentation, each wi
  This approach is especially well suited for segmenting densely packed cells.

 For a complete description of the methods used, please check out our
-[manuscript](https://elifesciences.org/articles/57613).
\ No newline at end of file
+[manuscript](https://elifesciences.org/articles/57613).
diff --git a/Python-API-Segmentation.md b/Python-API-Segmentation.md
index 99f1a71..f5abc7d 100644
--- a/Python-API-Segmentation.md
+++ b/Python-API-Segmentation.md
@@ -2,7 +2,7 @@

 In this section we will describe how to use the PlantSeg segmentation workflows from the python API.

-## API-Reference: [plantseg.predictions.functional.segmentation](https://github.com/hci-unihd/plant-seg/blob/master/plantseg/segmentation/functional/segmentation.py)
+## API-Reference: [plantseg.segmentation.functional.segmentation](https://github.com/hci-unihd/plant-seg/blob/master/plantseg/segmentation/functional/segmentation.py)
 * ***dt_watershed***
 ```python
 def dt_watershed(boundary_pmaps: np.array,
```

I wanted to inform the maintainers who are updating documentations right now. But by now the key changes seem to be fixing the typo `predictions` to `segmentation` in `plantseg.predictions.functional.segmentation` in Segmentation API (Home.md commit seems to be an empty one). Considering Wiki is a standalone repo anyways, I will change it now without going through formal processes. Thank you for pointing out!
