### ISSUE TITLE
Add the correct prediction channels in napari interface

### ISSUE THREAD

**Issue by Buglakova** [hci-unihd/plant-seg#183]
Hello,

When I use UNet prediction in Napari, the layers that are added are not consistent with the choices. For example, I know that `generic_plant_nuclei_3D` has both boundary and nuclei channels but if I choose "All" in the menu, it only adds the nuclei channel. As a result, I can't run the postprocessing step. I tried a few models and for all of them only one channel was added.

**Comment by qin-yu** [comment]
@Buglakova I'm fixing it in #165
