### ISSUE TITLE
Only PlantSeg v1.6.0 available on conda-forge

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#185]
After #176, no update to conda-forge yet. Do we do an automatic update on each version bump?

**Comment by qin-yu** [comment]
Remotely related to #145

**Comment by qin-yu** [comment]
Hopefully `v1.6.5` can be found in `-c [lcerrone](https://anaconda.org/lcerrone)` after 6564aaec82a8d5378d627c462491f1ac29a6d3f6 and 80a4c2bbae6642e5be896f8b1f603c5eb7030334

**Comment by qin-yu** [comment]
Success!

![image](https://github.com/hci-unihd/plant-seg/assets/17722010/a350dee7-8a51-437d-a584-f9a68ebb51bc)

Maybe I'll use Lorenzo's channel before conda-forge gets updated.

**Comment by qin-yu** [comment]
Hey @lorenzocerrone and @wolny 

The reason why we don't have updates on @conda-forge is that none of us joined the org and merge the PRs. I did it manually and nothing else has to be done now. Please check your email and join the org so you can approve the future PRs.

I'll close this issue now as it's fixed by https://github.com/conda-forge/plant-seg-feedstock/pull/6

![image](https://github.com/hci-unihd/plant-seg/assets/17722010/64e66f55-8606-4169-afe1-1bb63e49f0a1)

**Comment by wolny** [comment]
@qin-yu, we all joined the conda-forge before. Here's the readme of how to release a new version on conda-forge: https://github.com/hci-unihd/plant-seg/blob/master/conda-recipe/README.md#release-new-version-on-conda-forge-channel, but looks like you've figured it out already :)
