### ISSUE TITLE
Too many elements in extra-seg

### ISSUE THREAD

**Issue by lorenzocerrone** [hci-unihd/plant-seg#218]
![Screenshot from 2024-04-09 10-17-46](https://github.com/hci-unihd/plant-seg/assets/23013839/5b0b1600-c1a1-4375-829e-2a5e494c156a)

There are too many widget elements in the last tab, on my 16:9 screen, it makes the bottom part of the UI disappear (and I can not resize it). 

The solution could simply be to add a toggle for each widget in that tab. Do you agree @qin-yu ?

**Comment by qin-yu** [comment]
I fixed it in my own branch by rearranging widgets into one more tab. But that will make you changing docs so I thought I'll just do it after you finish the doc. But your solution is perfect and future proof. Let's do that. @lorenzocerrone

**Comment by qin-yu** [comment]
Hey @lorenzocerrone are you waiting for me or are you working on it already?

**Comment by lorenzocerrone** [comment]
No worries I can do it, but on Thursday. Today and tomorrow I can’t
