### ISSUE TITLE
Free gpu memory after predictions 

### ISSUE THREAD

**Issue by lorenzocerrone** [hci-unihd/plant-seg#39]
I was thinking that it would be cool to somehow free the gpu memory after planseg predictions.

**Comment by wolny** [comment]
I think we just need to invoke `torch.cuda.empty_cache()` after predictions.

**Comment by lorenzocerrone** [comment]
Yeah It should work, let's test it and merge in the next release

**Comment by wolny** [comment]
This was pushed to the master btw, we just need to release a new version
