### ISSUE TITLE
__init__() got multiple values for keyword argument 'basic_module'

### ISSUE THREAD

**Issue by rbuono** [hci-unihd/plant-seg#5]
Hi,

I followed the Linux install instructions and am getting the following error using the GUI:
> Unknown Error. Error type: <class 'TypeError'>
__init__() got multiple values for keyword argument 'basic_module'
> 

Tried running with and without data preprocessing (by preprocessing it in Fiji) and get the same.
Dataset is a confocal z-stack

Is there something I can do to fix this?

Thank you in advance.

Config is as follows:
`path: /home/user/Desktop/TC/samples/sample-1.tif
preprocessing:
  factor:
  - 2.000688936170213
  - 3.172168
  - 3.172168
  filter:
    filter_param: 1.0
    state: false
    type: gaussian
  order: 2
  save_directory: preprocessing
  state: false
segmentation:
  beta: 0.5
  name: MultiCut
  post_minsize: 50
  postprocessing:
    factor:
    - 1
    - 1
    - 1
    order: 0
    state: false
    tiff: false
  run_ws: true
  save_directory: MultiCut
  state: true
  ws_2D: true
  ws_minsize: 50
  ws_sigma: 2.0
  ws_threshold: 0.5
  ws_w_sigma: 0.0
unet_prediction:
  device: cuda
  model_name: generic_confocal_3d_unet
  model_update: false
  patch:
  - 32
  - 128
  - 128
  postprocessing:
    factor:
    - 1
    - 1
    - 1
    order: 2
    state: false
    tiff: false
  state: true
  stride:
  - 20
  - 100
  - 100
  version: best`

**Comment by lorenzocerrone** [comment]
Hi, 

Thanks a lot for sharing. The problem is related with our parallel project  and can be easy fixed by installing plantseg using the following command:
`conda create -n plant-seg -c lcerrone -c abailoni -c cpape -c awolny -c conda-forge pytorch-3dunet=1.0.3 plantseg`

Best,
Lorenzo

PS: a new version with several small improvement will come out in few days!

**Comment by rbuono** [comment]
It works!
Thank you.
