### ISSUE TITLE
failing to launch plantseg gui on macOS

### ISSUE THREAD

**Issue by sourabh-bhide** [hci-unihd/plant-seg#53]
Hi people ,
I am trying to use plantseg on my mac and I have trouble in launching. From what I understand gui display is failing and can't pin-point. I will eventually move to a linux system but would be nice to get it working on mac.
I would really appreciate help from you.
best,
Sourabh
sourabh.bhide@embl.com

macOS Catalina version 10.15.6
conda 4.7.12
Python 3.7.4
Docker version 19.03.12
XQuartz 2.7.11 (xorg-server 1.18.4)

“
bash-3.2$ docker run -it --rm -v /Users/saubhi/Desktop/SembLab/Data:/root/datasets -e DISPLAY=$DISPLAY wolny/plantseg

ERROR conda.cli.main_run:execute(31): Subprocess for 'conda run ['plantseg', '--gui']' command failed.  (See above for error)
Traceback (most recent call last):
  File "/root/miniconda3/envs/plant-seg/bin/plantseg", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/plant-seg/lib/python3.7/site-packages/plantseg/run_plantseg.py", line 24, in main
    PlantSegApp()
  File "/root/miniconda3/envs/plant-seg/lib/python3.7/site-packages/plantseg/gui/plantsegapp.py", line 43, in __init__
    self.plant_segapp = tkinter.Tk()
  File "/root/miniconda3/envs/plant-seg/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "/private/tmp/com.apple.launchd.mAtyr7ic37/org.macosforge.xquartz:0"

bash-3.2$ 

“

**Comment by wolny** [comment]
Hi Sourabh,
thanks for reaching out and creating the issue. From what I can tell by you're exception is that the docker image cannot connect to the xquartz display. Are you sure that the XQuartz is up and running on your system when you execute the `docker run ...`?

**Comment by sourabh-bhide** [comment]
Hi Adrian, 
thank you for your reply. It most certainly an issue with XQuartz. 
best,
Sourabh

**Comment by wolny** [comment]
Just for transparency: we were able to resolve this issue together with @sourabh-bhide. It seems to be related to docker not being able to connect to the UNIX socket created by `XQuartz 2.7.11`, i.e. `/private/tmp/com.apple.launchd.mAtyr7ic37/org.macosforge.xquartz:0` above.

Solution:
1. Install `socat`:
`brew install socat`

2. Create a TCP socket on port `6000` that just forwards to the Unix socket created by XQuartz:
`socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"`

3. Make sure that the port is open and listening:
`lsof -i TCP:6000`

4. Socat listens on all interfaces, so just grab the IP of one of your interfaces using `ifconfig` command. Let's assume your local IP is `192.168.0.47`, then use `192.168.0.47:0` as your new `DISPLAY` when executing docker run:
```
```
