### ISSUE TITLE
Add `LiftedMulticut' to the list of supported algorithms in UI

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#57]
`LiftedMulticut` is now supported from within the YAML file configuration. It should also be added to the UI.
If added to the UI we would need additional field to specify the `nuclei_predictions_path` option. In order to keep the UI generic we could just add generic text field `additional_attributes` where the user could provide comma separated values, e.g.
`nuclei_predictions_path: /home/user/nuclei_pmaps, some_attr: XYZ`.

**Comment by lorenzocerrone** [comment]
Yeah sounds good, but we should then parse the string into a dict.. do you have a good way to do it?

**Comment by wolny** [comment]
ok, this is an advanced feature with no easy way to expose in the UI. Let's keep it config-only
