### ISSUE TITLE
manifest not found for tag latest with docker run

### ISSUE THREAD

**Issue by Orzzet** [hci-unihd/plant-seg#6]
Hi, 

I tried running the docker image following the readme and this happened:

```
$ docker run -it --rm -v /Descargas/data:/root/datasets -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY wolny/plantseg
Unable to find image 'wolny/plantseg:latest' locally
docker: Error response from daemon: manifest for wolny/plantseg:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```
After that I checked the tags available for the project in this url: [https://hub.docker.com/v2/repositories/wolny/plantseg/tags](https://hub.docker.com/v2/repositories/wolny/plantseg/tags)

I tried again with the tag '1.0.1' and it worked:
```
$ docker run -it --rm -v /Descargas/data:/root/datasets -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY wolny/plantseg:1.0.1
Unable to find image 'wolny/plantseg:latest' locally
1.0.1: Pulling from wolny/plantseg
```

**Comment by wolny** [comment]
Hi @Orzzet,

thanks for reporting the issue. Indeed the `latest` tag was not pushed to the docker hub. I've pushed the `latest` tag which points to the newest version of the image. 
I've also updated our release docs to prevent this happening in the future.

Cheers!
