### ISSUE TITLE
Is this OK for RTX 3060 ti?

### ISSUE THREAD

**Issue by lenlabcangay** [hci-unihd/plant-seg#64]
Hi,
I tested the software on my PC (Ryzen 3800x 3.9GHz, 48GB RAM, RTX 3060ti) and it took 26 minutes to perform the pipeline on a confocal stack of 145x145x50um (50 slices).
Is this performance normal for the PC? I feel it was too slow. In fact, the GPU was not used much.
Does the software support the RTX 30 series?
Thank you very much!

**Comment by lorenzocerrone** [comment]
Hi,

PlantSeg pipeline has two main steps 'CNN predictions' and 'Segmentation'. Is 26 minutes the overall runtime or only is it the CNN predictions runtime?

If 26min is the total runtime, than probably is the 'Segmentation' step fault. Currently, the 'Segmentation' step can't use the GPU and is not parallelized, so the runtime you mentioned sounds plausible to me. Unfortunately, the 'segmentation' step takes most of the total runtime.

About the support for RTX 30 series, yes it's supported but we do not benefit from the tensor core yet. While it might be good to add support for tensor core in the future (especially for training), the current bottleneck of PlantSeg is the segmentation. So it would only marginally improve the overall runtime. 

Best,

Lorenzo

**Comment by lenlabcangay** [comment]
Thanks for the reply. 
26min is the overall runtime. The prediction step may take 5-6 min.
Cheers,
