### ISSUE TITLE
Slices are skipped + ghost signal

### ISSUE THREAD

**Issue by lenlabcangay** [hci-unihd/plant-seg#65]
[problems PlantSeg Sepal.zip](https://github.com/hci-unihd/plant-seg/files/5924852/problems.PlantSeg.Sepal.zip)

Hello,
I am testing PlantSeg with my sepal samples (only Prediction, I don't use Segmentation yet), and I got some issues:
- Slices were frequently skipped; black slices were returned. I tried with a cropped image which contain only the sample (less black space), and reduced the patch size, but the problem persisted.
- Ghost signal appears in first slices when there are no fluorescent signal. Of course I can remove them, but how do the ghost signal appear?
- There is halo surrounding true signal.
- Sometimes the program stays for a very long time at "Sending the model to cuda:0" step (>30 min). Sometimes it works very fast which I assume how it should (finished in <6min). There are some issues of consistency there.

I attached the input and output images, as well as PlantSeg parameter here so that you can have a look.
For those slices that are treated, the results seem to be excellent.
Thanks for your time.
Cheers,

**Comment by lenlabcangay** [comment]
Hello,
Thanks for your reply.
- Yes, the halo seems not to affect the segmentation.
- I am using RTX 3060ti, Nvidia 460.39, Cuda 10.2 runtime, Ubuntu 18.04. 
The 'sending the model to cuda' is quite persistent. I have to kill the software many times before getting one running as expected. 
It is really a pity that the software can't use more than one CPU thread. It would be great if it is better optimized, given that you want this software to be used widely and for years in the future.
- Do you have a recommended OS/Cuda version?
Thanks again for the good work!

**Comment by lorenzocerrone** [comment]
Hello, 

So after some troubleshooting, I found that the problem with the skipped z-slices comes from the patch-size/stride-size. In short, the patch size should be more than 8 voxels in z (and 16 in xy) bigger than the stride size.. so in your case, you might want to either increase the patch size on z to 32 (or more) or set the stride to accurate in the gui.

We have just pushed a new release 1.3.0 where you'll get a warning if the patch/stride combination is not optimal. Moreover, there is an additional pre-trained model that might be useful for you.

"Do you have a recommended OS/Cuda version?" Not really I have tested plantseg on Ubuntu/Manjaro/Fedora without major issues. I have mostly used cuda 10.2 so far. But I have on my personal machine cuda 11 and I have not experienced any issues there. I have no experience with RTX cards, unfortunately. 

About the Multi-Threading, I agree with you we should leverage it more but we have not yet a plan on that.
