### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/plant-seg#69]
The current installation instructions don't work:
```
(main38) pape@gpu7:~/Work/my_projects$ conda create -n plant-seg -c lcerrone -c abailoni -c cpape -c awolny -c conda-forge nifty=vplantseg1.0.8 pytorch-3dunet=1.2.5 plantseg
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
pytorch-3dunet=1.2.5 -> h5py -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.6']
pytorch-3dunet=1.2.5 -> python[version='>=3.7,<3.8.0a0']

Package pytorch-3dunet conflicts for:
pytorch-3dunet=1.2.5
plantseg -> pytorch-3dunet

Package pillow conflicts for:
pytorch-3dunet=1.2.5 -> pillow[version='<7']
pytorch-3dunet=1.2.5 -> scikit-image -> pillow[version='>=1.7.8|>=2.1.0|>=4.3.0|>=4.1.1']

Package scipy conflicts for:
pytorch-3dunet=1.2.5 -> scipy
pytorch-3dunet=1.2.5 -> scikit-image -> scipy[version='>=0.17|>=0.19|>=0.9']

Package libgfortran5 conflicts for:
pytorch-3dunet=1.2.5 -> scipy -> libgfortran5[version='>=9.3.0']
nifty=vplantseg1.0.8 -> hdf5[version='>=1.10'] -> libgfortran5[version='>=9.3.0']

Package blas conflicts for:
nifty=vplantseg1.0.8 -> numpy[version='>=1.15'] -> blas[version='*|1.1|1.0|1.0',build='openblas|mkl|openblas']
pytorch-3dunet=1.2.5 -> scikit-learn -> blas[version='*|*|1.1|1.0|1.0',build='mkl|openblas|mkl|openblas']
plantseg -> pytorch -> blas[version='*|*|1.0|1.1|1.0',build='mkl|openblas|openblas|mkl|openblas']

Package nifty conflicts for:
nifty=vplantseg1.0.8
plantseg -> gasp -> nifty=1.0.9
```

Btw, I put nifty on conda-forge recently and I would very much encourage you to use it:
https://github.com/conda-forge/nifty-feedstock.

Also, this: `-c lcerrone -c abailoni -c cpape -c awolny -c conda-forge` doesn't look like a good idea for reproducible environments ...

**Comment by lorenzocerrone** [comment]
Thank you for letting us know, It's weird I tested the installation only few days ago without any issues. Anyway that's good occasion to clean the conda recipe

**Comment by lorenzocerrone** [comment]
The install should work now and the install command is a bit simplified:
`conda create -n plant-seg -c lcerrone -c abailoni -c cpape -c awolny -c conda-forge plantseg` 

nifty is still from Alberto's channel but it seems to have no effect on the MC workflow. I agree, it would be way nicer to use the conda-forge version, I will discuss this with Alberto. 

I agree with you that the the long chain of channels is not the best option and it will fail again in the future. 
I can think of one fix, we can fork our dependencies on hci-unihd and create a shared plantseg conda channel where we push builds that are critical for plant-seg. What do you think? @constantinpape @wolny  Sounds good for you or do you have a better suggestion?

**Comment by constantinpape** [comment]
> I can think of one fix, we can fork our dependencies on hci-unihd and create a shared plantseg conda channel where we push builds that are critical for plant-seg. What do you think? @constantinpape @wolny Sounds good for you or do you have a better suggestion?

I think the ideal solution would be to get most dependencies on conda-forge and try to eliminate custom channels if possible (I am planning to bring elf on conda-forge soon as well).
But if you don't want to push some of them on conda-forge, then yes having a dedicated plantseg channel would be a good solution.
