### ISSUE TITLE
GUI improvements: move 'Auto re-scale' button to Data Pre-Processing stage

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#7]
Let's keep the 'Rescaling Factor' as it is with the default (1,1,1) value (explain clearly that it's going to **multiply** the size of each axis) and provide the Auto re-scale button just below

**Comment by lorenzocerrone** [comment]
I changed add the button on the side and made the text in the popup more explanatory, let me know if you like it

**Comment by wolny** [comment]
LGTM
