### ISSUE TITLE
pipeline step: 'cnn post processing' - input files path is empty 

### ISSUE THREAD

**Issue by ellapenny** [hci-unihd/plant-seg#72]
Hiya sorry have another issue: 

The cnn predictions appear to be saved in the PreProcessing folder:
....
`Executing pipeline step: 'cnn_prediction'. Parameters: '{'state': True, 'model_name': 'generic_confocal_3d_unet', 'device': 'cpu', 'patch': [8, 32, 32], 'stride': 'Balanced', 'version': 'best', 'model_update': False}'. Files ['/root/datasets/Crop/PreProcessing/Stack7crop51.h5'].`

But when Executing pipeline step: 'cnn_postprocessing', the 'input file path is empty':
` Executing pipeline step: 'cnn_postprocessing'. Parameters: '{'state': True, 'tiff': False, 'output_type': 'data_uint8', 'factor': [0.41504768632991873, 0.226928895612708, 0.24748391354561955], 'order': 2, 'save_raw': False}'. Files [].`

Not sure why, because the .h5 file in the PreProcessing folder is 75Mb so definitely there. Any advice?

**Comment by lorenzocerrone** [comment]
Hi, 

Thank you for testing PlantSeg and sorry for having not answered on the other issue. We are not yet sure what is the problem there, probably an issue with the XServer in Windows. Unfortunately, we are not able to test Plantseg extensively on windows.

I am not sure if I have understood the issue you are experiencing here. 
"The cnn predictions appear to be saved in the PreProcessing folder:" The file path showed there is the input file to the `cnn_predictions` not the output. Following your setup the predictions should be saved in "'/root/datasets/Crop/PreProcessing/generic_confocal_3d_unet/Stack7crop51_predictions.h5'", can you see this file? 

So in the second case the list of input files is empty. Are you executing the postprocessing directly after the cnn_predictions? or are you running them in different runs?
That said this seems very strange, I can only reproduce this if in the plantseg config I use an empty directory as input path.

Best, 
Lorenzo

PS, Some unrelated details I noticed. It seems that your rescaling factor is very large (~ x 5) on X-Y this could introduce many defects in the segmentation. If the predictions results are not good, I would advice you to reduce the scaling or to check out another confocal model (we have just released some new models trained on meristem). Moreover the 'patch': [8, 32, 32], I would suggest you to increase it if your hardware allows it.

**Comment by ellapenny** [comment]
Hiya, 

Should've made it clear - these two lines of code were the penultimate 2 lines of the same error code. These are all appearing in the same run. The root/datasets/Crop/PreProcessing/**generic_confocal_3d_unet** folder does not appear (though has appeared during other trials before the system crashed). Do you have anything i can try to get this step to work?

Thanks for the other advice! I'm optimistic i will eventually get some segmented data!

Best,
Ella

**Comment by lorenzocerrone** [comment]
Hi, 

mmh unfortunately, I am not yet sure what the issue could be. I have never encounter this bug before.  

Could share with me a small image sample and the plantseg config file you are using? Maybe I can try to reproduce your issue from that.

Thanks! 

Lorenzo

**Comment by ellapenny** [comment]
Hiya, 

This is the link to the data/config : 
https://drive.google.com/drive/folders/1pwl-VkXFsVAfzSQMI_frRIJQsUKh9tAu?usp=sharing (if that's the wrong config file i also have a manual record of config) 

I actually managed one complete pipeline yesterday afternoon - but not yet reproducible

Thanks, 
Ella

**Comment by lorenzocerrone** [comment]
Hi,

The config file you posted is a single process config, it's mostly used by us for debugging but it can not run plantseg.  The full config is a similar yaml file, you can export the current config from the gui by going in File>save. for an example see "plantseg-issue72-config.yaml" in the google drive link. 

The partial config and the file are alright, and everything seems fine to me. I think (fear) the problem might be with the Docker version of plant-seg. If that's the case I will need some to look into it and unfortunately I can not at the moment.

On the positive side, When I tested plantseg on the small sample (although the resolution is very different from any model we currently have) the results seemed "alright-ish" :)  the sample processed is here:
https://drive.google.com/drive/folders/1steUYi2gCmIAbLhMO3VgdkcOhX1CEUwI?usp=sharing

You could test your plantseg by trying to run the same config I have used "plantseg-issue72-config.yaml" (just remember to change the file path with your own file path.)

Do you have access to a linux machine to test it there? Alternatively you could use the Windows linux subsystem to install Plantseg https://docs.microsoft.com/en-us/windows/wsl/install-win10 .
I have tested this option and it works fine, but I have not yet managed to write down the installation procedure.
the steps are:
- installing the windows linux subsystem (and a Xserver, I have personally only used VcXsrv but probably any alternative should do the job)
- install ubuntu from the Microsoft store
- setup the display in the `.bashrc` file (there are several guides on the topic: https://medium.com/@dhanar.santika/installing-wsl-with-gui-using-vcxsrv-6f307e96fac0)
- install anaconda python and plantseg following the linux instructions in the main `README.md`

I hope you find this helpful, please let me know if you get additional problems.

Best, 

Lorenzo

**Comment by ellapenny** [comment]
I will investigate all of these - thank you so much. This has been an enormous help.

Best,
Ella

**Comment by lorenzocerrone** [comment]
Sounds good, and good luck with your experiments! 

I will now close the issue, but please let us know if you encounter further problems. 

Best, 

Lorenzo
