### ISSUE TITLE
Cannot skip CNN processin step from the pipeline

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#76]
If the boundary maps are available it should be possible to just disable the cnn processing (`state: False` in the config) and just run the segmentation algorithm directly, but currently even if the step is disabled in the config, PlantSeg still tries to run it.

**Comment by lorenzocerrone** [comment]
Very weird, I have just tested it and it works fine on my installation. Is the boundary maps h5 formatted as the default plantseg?

**Comment by wolny** [comment]
Yes, you're right I've just tried now with the GASP pipeline and it works... this seem to be related only to the LMC. I'm closing this, sorry
