### ISSUE TITLE
Change the names of the hyper-params to more readable

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#9]
1. Filter -> Filter (Optional)
2. Beta -> Under-/Over-segmentation factor
3. WS -> Watershed
4. WS Threshold -> Probability Maps Threshold (?)
5. WS Minimum Size -> Superpixel Minimum Size (?)
6. Minimum Size -> Cell Minimum Size

**Comment by lorenzocerrone** [comment]
I think that the following still need some thoughts: 
- Beta -> Under-/Over-segmentation factor (too long)
- WS Threshold -> Probability Maps Threshold (?) (probability map could be confusing for the user)
I am ok with all others :)

**Comment by lorenzocerrone** [comment]
![Screenshot from 2020-02-14 17-44-06](https://user-images.githubusercontent.com/23013839/74550509-ca1c0280-4f51-11ea-85e4-da3e51877daf.png)

On a big screen the new names looks good.. I hope they are not too long for low-res/small monitors.

**Comment by wolny** [comment]
Looks good to me!
