### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by soans1994** [hci-unihd/plant-seg#94]
hello author,

i want to know about your evaluation metrics code. can i use it if my dataset has raw and segment labels as png. or should do i need some other annotation format of labels? which approach is better.

thank you

**Comment by lorenzocerrone** [comment]
Hi,

I am very sorry for the late answer. The evaluation only works with "h5". 
The label images you have should work fine, but you will need to export them in h5. This can be done using Fiji or a simple python script. 
The raw images is not needed for the evaluation. The evaluation requires only the `segmentation` you want to evaluate (the output from plant-seg as an example) and a gold standard `ground truth` labels image that has been proofread by an expert. The evaluation script will compare the two using the metrics we describe in the manuscript.

To summarize, for the evaluation you will need to:
 * create an h5 file for each of the `ground truth labels` images and one for each `segmentation` image.
 * Then you will need to prepare a configuration file like this https://github.com/hci-unihd/plant-seg/blob/master/evaluation/evaluation_config.yml , the comments in the file should help you filling correctly the relevant fields. 
 * Running the evaluation script following the instructions in https://github.com/hci-unihd/plant-seg/blob/master/evaluation/README.md

Please if you have more question do not hesitate contacting me again.

Best,

Lorenzo

**Comment by soans1994** [comment]
@lorenzocerrone thank you very much i will try using h5 format.
